address=""
port=9187
options=[]
query-path=""

[data-source]
name=""
uri=""
user=""
user-file=""
pass=""
pass-file=""

# Some examples of adding custom queries

# [queries.pg_replication]
# query = "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))::INT as lag"
#   [[queries.pg_replication.metrics]]
#     [queries.pg_replication.metrics.lag]
#     usage = "GAUGE"
#     description = "Replication lag behind master in seconds"

# [queries.pg_postmaster]
# query = "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
#   [[queries.pg_postmaster.metrics]]
#     [queries.pg_postmaster.metrics.start_time_seconds]
#     usage = "GAUGE"
#     description = "Time at which postmaster started"

# [queries.pg_stat_user_tables]
# query = "SELECT schemaname, relname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup, n_mod_since_analyze, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze, vacuum_count, autovacuum_count, analyze_count, autoanalyze_count FROM pg_stat_user_tables"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.schemaname]
#     usage = "LABEL"
#     description = "Name of the schema that this table is in"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.relname]
#     usage = "LABEL"
#     description = "Name of this table"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.seq_scan]
#     usage = "COUNTER"
#     description = "Number of sequential scans initiated on this table"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.seq_tup_read]
#     usage = "COUNTER"
#     description = "Number of live rows fetched by sequential scans"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.idx_scan]
#     usage = "COUNTER"
#     description = "Number of index scans initiated on this table"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.idx_tup_fetch]
#     usage = "COUNTER"
#     description = "Number of live rows fetched by index scans"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_tup_ins]
#     usage = "COUNTER"
#     description = "Number of rows inserted"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_tup_upd]
#     usage = "COUNTER"
#     description = "Number of rows updated"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_tup_del]
#     usage = "COUNTER"
#     description = "Number of rows deleted"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_tup_hot_upd]
#     usage = "COUNTER"
#     description = "Number of rows HOT updated (i.e., with no separate index update required)"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_live_tup]
#     usage = "GAUGE"
#     description = "Estimated number of live rows"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_dead_tup]
#     usage = "GAUGE"
#     description = "Estimated number of dead rows"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.n_mod_since_analyze]
#     usage = "GAUGE"
#     description = "Estimated number of rows changed since last analyze"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.last_vacuum]
#     usage = "GAUGE"
#     description = "Last time at which this table was manually vacuumed (not counting VACUUM FULL)"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.last_autovacuum]
#     usage = "GAUGE"
#     description = "Last time at which this table was vacuumed by the autovacuum daemon"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.last_analyze]
#     usage = "GAUGE"
#     description = "Last time at which this table was manually analyzed"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.last_autoanalyze]
#     usage = "GAUGE"
#     description = "Last time at which this table was analyzed by the autovacuum daemon"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.vacuum_count]
#     usage = "COUNTER"
#     description = "Number of times this table has been manually vacuumed (not counting VACUUM FULL)"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.autovacuum_count]
#     usage = "COUNTER"
#     description = "Number of times this table has been vacuumed by the autovacuum daemon"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.analyze_count]
#     usage = "COUNTER"
#     description = "Number of times this table has been manually analyzed"
#   [[queries.pg_stat_user_tables.metrics]]
#     [queries.pg_stat_user_tables.metrics.autoanalyze_count]
#     usage = "COUNTER"
#     description = "Number of times this table has been analyzed by the autovacuum daemon"
# [queries.pg_database]
# query = " SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
#   [[queries.pg_database.metrics]]
#     [queries.pg_database.metrics.datname]
#     usage = "LABEL"
#     description = "Name of the database"
#   [[queries.pg_database.metrics]]
#     [queries.pg_database.metrics.size]
#     usage = "GAUGE"
#     description = "Disk space used by the database"
