{{~#if cfg.scrapers}}
scrapers:
{{~#each cfg.scrapers as |name scraper|}}
  {{name}}:
    url: {{scraper.url}}
    period: {{scraper.period}}
    format: {{scraper.format}}
    {{~#if scraper.labels}}
    labels:
    {{~#each scraper.labels as |key value|}}
      {{key}}: {{value}}
    {{~/each}}
    {{~/if}}
    {{~#if scraper.metrics}}
    metrics:
    {{~#each scraper.metrics as |metric|}}
      - {{metric}}
    {{~/each}}
    {{~/if}}
    {{~#if scraper.headers}}
    headers:
    {{~#each scraper.headers as |key value|}}
      {{key}}: {{value}}
    {{~/each}}
    {{~/if}}
    {{~#if scraper.pool}}
    pool: {{scraper.pool}}
    {{~/if}}
{{~/each}}
{{~/if}}

{{~#if cfg.sinks}}
sinks:
{{~#each cfg.sinks as |name sink|}}
  {{name}}:
    url: {{sink.url}}
    token: {{sink.token}}
    {{~#if sink.token-header}}
    token-header: {{sink.token-header}}
    {{~/if}}
    {{~#if sink.selector}}
    selector: {{sink.selector}}
    {{~/if}}
    {{~#if sink.ttl}}
    ttl: {{sink.ttl}}
    {{~/if}}
    {{~#if sink.size}}
    size: {{sink.size}}
    {{~/if}}
    {{~#if sink.parallel}}
    parallel: {{sink.parallel}}
    {{~/if}}
    {{~#if sink.keep-alive}}
    keep-alive: {{sink.keep-alive}}
    {{~/if}}
{{~/each}}
{{~/if}}

{{~#if cfg.labels}}
labels:
{{~#each cfg.labels as |name value|}}
  {{name}}: {{value}}
{{~/each}}
{{~/if}}

parameters:
  source-dir: {{pkg.svc_data_path}}/{{cfg.parameters.source-dir}}
  sink-dir: {{pkg.svc_data_path}}/{{cfg.parameters.sink-dir}}
  scan-period: {{cfg.parameters.scan-period}}
  batch-count: {{cfg.parameters.batch-count}}
  batch-size: {{cfg.parameters.batch-size}}
  log-file: {{pkg.svc_var_path}}/{{cfg.parameters.log-file}}
  log-level: {{cfg.parameters.log-level}}
  timeout: {{cfg.parameters.timeout}}
  router-parallel: {{cfg.parameters.router-parallel}}
  {{~#if cfg.parameters.metrics}}
  metrics: {{cfg.parameters.metrics}}
  {{~/if}}
  filesystem-threads: {{cfg.parameters.filesystem-threads}}
  {{~#if cfg.parameters.backoff}}
  backoff:
    initial: {{cfg.parameters.backoff.initial}}
    max: {{cfg.parameters.backoff.max}}
    multiplier: {{cfg.parameters.backoff.multiplier}}
    randomization: {{cfg.parameters.backoff.randomization}}
  {{~/if}}
